# Generated by Django 5.2 on 2025-06-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pickup', models.CharField(max_length=200)),
                ('dropoff', models.CharField(max_length=200)),
                ('equipment', models.CharField(max_length=50)),
                ('weight', models.PositiveIntegerField()),
                ('pickup_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
