# Generated by Django 5.2 on 2025-06-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truckingllc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='equipment',
            field=models.CharField(choices=[('dry-van', "53' Dry Van"), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('power-only', 'Power Only'), ('hotshot', 'Hotshot')], max_length=50),
        ),
    ]
